# my global config
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["54.179.37.78:9100"]

  - job_name: "Ansible_1"
    static_configs:
      - targets: ["172.31.36.38:9100"]


  - job_name: "Ansible_2"
    static_configs:
      - targets: ["172.31.34.180:9100"]

  - job_name: "jenkins_server"
    static_configs:
      - targets: ["13.215.200.96:9100"]
