# my global config
global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["13.250.42.33:9100"]

  - job_name: "jenkins_server"
    static_configs:
      - targets: ["13.212.254.237:9100"]

  - job_name: "jenkins_agent
    static_configs:
      - targets: ["18.136.102.32:9100"]
       